site_name: 'Brian Naja'
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
permalink: /:categories/:title
paginate: 5
prose:
  siteurl: "http://briannaja.com"
  rooturl: "_posts"
  media: "images"
  
  metadata:
    _posts:
        title: "Post Title"
        
        - name: "layout"
        field:
          element: "text"
          label: "Layout"
          value: "post"
          
      
        category: "Post Category"
        
        
