site_name: 'Brian Naja'
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
permalink: /:categories/:title
paginate: 5
prose:
  siteurl: "http://briannaja.com"
  rooturl: "_posts"
  media: "images"
  
  metadata:
     _posts:
         title: "Post Title"
         layout: "post/video-post"      
       name: "category"
        field:
         element: "select"
         label: "something"
         placeholder: "Select an Item"
         options:
            post: "post"
              value: "post"
            video: "video"
              value: "video"
          selected: "post"
        category: "post/video"
        
        
