site_name: 'Brian Naja'
markdown: rdiscount
rdiscount:
  extensions: [smart]
pygments: true
permalink: /:categories/:title
paginate: 5
prose:
  siteurl: "http://briannaja.com"
  rooturl: "_posts"
  media: "images"
  
  metadata:
    _posts:
        title: "categories"
        field:
          element: "hidden"
          value:
             "post"
